test:
  init:
    hp: 1000
    hp_regen: 0
    mp: 1000

    attack: 500
    accuracy: 1
    speed: 1
    counter_resist: 0.5
    crit_chance: 0.5
    crit_mult: 1.5

    resist: 0.5
    mitigation: 0.5
    evade: 0.5